-- Generated by OmaSettings (omasettings:managed) — do not edit by hand.
-- Every value here was set from the OmaSettings window; delete a line
-- to hand that setting back to your own config.


-- Workspaces set up from the Workspaces page.
hl.workspace_rule({ workspace = "1", persistent = true, default_name = "main" })
